% Plot the Vs model generated by Litho1.0 and the opt.model file generated by AkiEstimate
% Plots are mimicing fig4(b) in Hawkins' AkiEstimate paper
% Aug. 25, 2021 -- Siyu Xue

addpath(genpath('/Users/sxue3/Documents/Figures/SEMLAB'));
akimodel = '/Users/sxue3/Documents/Figures/data/Fig6_model/XDmodel.txt';
lithomodel = '/Users/sxue3/Documents/Figures/data/Fig6_model/XD-RUNG_XD-MTAN.txt';
deplim = [-1 50];
%% PLOT THE TWO Vs MODEL FILES
% STEP 1: PLOT THE AKI MODEL
subplot(1,4,2)
text(48, 2.4,'(b)','fontsize',15);
akiXD = fopen(akimodel); 
temp = fgetl(akiXD);
temp = fgetl(akiXD);
temp = str2num(fgetl(akiXD));
nElem = temp(2);

noint = 1000; % number of interpolation points
Xtop = 0;
hold on

for i = 1:nElem

    % plot the density (rho)
    temp = str2num(fgetl(akiXD));
    depth = temp(1)/1000;  % convert km to m
    rho = str2num(fgetl(akiXD));
     
    % plot Vs
    vs = str2num(fgetl(akiXD));
    P = vs(1);
    if Xtop ~= 0
        oldyvs = yvs;
        yvs = vs(2:end)./1000;
        plot([Xtop Xtop],[oldyvs(end) yvs(1)],'Color','k', 'LineWidth',2);
    else
        yvs = vs(2:end)./1000;
    end
    Xbot = Xtop + depth;
    X = [Xtop Xbot];
    
    NGLL = P+1; 				% = number of GLL nodes per element
    [iglob,xcoor,nglob] = mesh1d(X,NGLL);	% creates the SEM grid	
    xcoor(1) = Xtop;
    xi = linspace(Xtop, Xbot, noint);
    db = interp1_sem(xcoor,xi ,iglob); %	initialize 
    yi = interp1_sem(yvs,db ,iglob); % 	interpolate

    plot(xi, yi,'k', 'LineWidth',2)
    plot(xcoor, yvs, 'ro');

    Xi = str2num(fgetl(akiXD));
    vpvs = str2num(fgetl(akiXD));
    
    % reset the current depth
    Xtop = Xbot;
end

% plot the last layer in the Aki model (Vs)
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
Xbot = Xtop + 30;
yvs = temp(1)/1000;
plot([Xtop Xtop],[yi(end) yvs],'Color','k', 'LineWidth',2);
X = [Xtop Xbot];
plot(X,[yvs,yvs],'Color','k', 'LineWidth',2);


%xlabel('Depth (km)');
ylabel('V_s (km/s)');
ylim([2 6]);
xlim(deplim);
set(gca, 'XGrid','on');
view(90,-90);
set(gca, 'XDir','reverse');
box on;
hold off

%% Plot the rho model from Aki
subplot(1,4,1)
text(48, 1.8,'(a)','fontsize',15);
akiXD = fopen(akimodel); 
temp = fgetl(akiXD);
temp = fgetl(akiXD);
temp = str2num(fgetl(akiXD));
nElem = temp(2);

noint = 1000; % number of interpolation points
Xtop = 0;
hold on

for i = 1:nElem

    % plot the density (rho)
    temp = str2num(fgetl(akiXD));
    depth = temp(1)/1000;  % convert km to m
    rho = str2num(fgetl(akiXD));
    P = rho(1);
    
    if Xtop ~= 0
        oldyvs = yrho;
        yrho = rho(2:end)./1000;
        plot([Xtop Xtop],[oldyvs(end) yrho(1)],'Color','k', 'LineWidth',2);
    else
        yrho = rho(2:end)./1000;
    end
    
    Xbot = Xtop + depth;
    X = [Xtop Xbot];
    
    NGLL = P+1; 				% = number of GLL nodes per element
    [iglob,xcoor,nglob] = mesh1d(X,NGLL);	% creates the SEM grid	
    xcoor(1) = Xtop;
    xi = linspace(Xtop, Xbot, noint);
    db = interp1_sem(xcoor,xi ,iglob); %	initialize 
    yi = interp1_sem(yrho,db ,iglob); % 	interpolate
    plot(xi, yi,'k', 'LineWidth',2);
    plot(xcoor, yrho, 'ro');
     
    vs = str2num(fgetl(akiXD));
    Xi = str2num(fgetl(akiXD));
    vpvs = str2num(fgetl(akiXD));
    
    % reset the current depth
    Xtop = Xbot;
end

% plot the last layer in the Aki model (rho)
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
Xbot = Xtop + 30;
yrho = temp(1)/1000;
plot([Xtop Xtop],[yi(end) yrho],'Color','k', 'LineWidth',2);
X = [Xtop Xbot];
plot(X,[yrho,yrho],'Color','k', 'LineWidth',2);

xlabel('Depth (km)');
ylabel('Density (g/cm^3)');
ylim([1.5 4]);
xlim(deplim);
set(gca, 'XGrid','on');
view(90,-90);
set(gca, 'XDir','reverse');
box on;

hold off
%% Plot the Xi model from Aki
subplot(1,4,3)
text(48, 0.6,'(c)','fontsize',15);
akiXD = fopen(akimodel); 
temp = fgetl(akiXD);
temp = fgetl(akiXD);
temp = str2num(fgetl(akiXD));
nElem = temp(2);

noint = 1000; % number of interpolation points
Xtop = 0;
hold on

for i = 1:nElem

    temp = str2num(fgetl(akiXD));
    depth = temp(1)/1000;  % convert km to m
    rho = str2num(fgetl(akiXD));
    vs = str2num(fgetl(akiXD));
    
    % plot Xi
    Xi = str2num(fgetl(akiXD));
    P = Xi(1);
    
    if Xtop ~= 0
        oldyvs = yXi;
        yXi = Xi(2:end);
        plot([Xtop Xtop],[oldyvs(end) yXi(1)],'Color','k', 'LineWidth',2);
    else
        yXi = Xi(2:end);
    end
    
    Xbot = Xtop + depth;
    X = [Xtop Xbot];
    
    NGLL = P+1; 				% = number of GLL nodes per element
    [iglob,xcoor,nglob] = mesh1d(X,NGLL);	% creates the SEM grid	
    xcoor(1) = Xtop;
    xi = linspace(Xtop, Xbot, noint);
    db = interp1_sem(xcoor,xi ,iglob); %	initialize 
    yi = interp1_sem(yXi,db ,iglob); % 	interpolate
    plot(xi, yi,'k', 'LineWidth',2);
    plot(xcoor, yXi, 'ro');
    vpvs = str2num(fgetl(akiXD));
    
    % reset the current depth
    Xtop = Xbot;
end

% plot the last layer in the Aki model (rho)
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
Xbot = Xtop + 30;
yXi = temp(1);
plot([Xtop Xtop],[yi(end) yXi],'Color','k', 'LineWidth',2);
X = [Xtop Xbot];
plot(X,[yXi,yXi],'Color','k', 'LineWidth',2);

% plot the reference curve
plot([-1 50],[1 1],'Color','k', 'LineWidth',2,'LineStyle',':');


%xlabel('Depth (km)');
ylabel('Xi');
ylim([0.5 1.5]);
xlim(deplim);
set(gca, 'XGrid','on');
view(90,-90);
set(gca, 'XDir','reverse');
box on;

hold off

%% Plot the Vp/Vs model from Aki
subplot(1,4,4)
text(48, 1.3,'(d)','fontsize',15);
akiXD = fopen(akimodel); 
temp = fgetl(akiXD);
temp = fgetl(akiXD);
temp = str2num(fgetl(akiXD));
nElem = temp(2);

noint = 1000; % number of interpolation points
Xtop = 0;
hold on

for i = 1:nElem

    temp = str2num(fgetl(akiXD));
    depth = temp(1)/1000;  % convert km to m
    rho = str2num(fgetl(akiXD));
    vs = str2num(fgetl(akiXD));
    Xi = str2num(fgetl(akiXD));

    % plot Vp/Vs
    vpvs = str2num(fgetl(akiXD));
    P = vpvs(1);
    
    if Xtop ~= 0
        oldyvs = yvpvs;
        yvpvs = vpvs(2:end);
        plot([Xtop Xtop],[oldyvs(end) yvpvs(1)],'Color','k', 'LineWidth',2);
    else
        yvpvs= vpvs(2:end);
    end
    
    Xbot = Xtop + depth;
    X = [Xtop Xbot];
    
    NGLL = P+1; 				% = number of GLL nodes per element
    [iglob,xcoor,nglob] = mesh1d(X,NGLL);	% creates the SEM grid	
    xcoor(1) = Xtop;
    xi = linspace(Xtop, Xbot, noint);
    db = interp1_sem(xcoor,xi ,iglob); %	initialize 
    yi = interp1_sem(yvpvs,db ,iglob); % 	interpolate
    plot(xi, yi,'k', 'LineWidth',2);
    plot(xcoor, yvpvs, 'ro');
    
    % reset the current depth
    Xtop = Xbot;
end

% plot the last layer in the Aki model (rho)
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
temp = str2num(fgetl(akiXD));
Xbot = Xtop + 30;
yvpvs = temp(1);
plot([Xtop Xtop],[yi(end) yvpvs],'Color','k', 'LineWidth',2);
X = [Xtop Xbot];
plot(X,[yvpvs,yvpvs],'Color','k', 'LineWidth',2);

%xlabel('Depth (km)');
ylabel('V_p/ V_s');
ylim([1.2 2.1]);
xlim(deplim);
set(gca, 'XGrid','on');
view(90,-90);
set(gca, 'XDir','reverse');
box on;

hold off

%% STEP 2: PLOT LITHO1.0 MODEL

% plot the Vs model
lithoXD = fopen(lithomodel);
temp = fgetl(lithoXD);
nElem = str2num(temp)-1;
Xtop = 0;

subplot(1,4,2);
hold on
for i = 1:nElem
    temp = str2num(fgetl(lithoXD));
    depth = temp(1);
    Xbot = Xtop + depth;
    if Xtop ~= 0
        oldyvs = yvs;
        yvs = temp(3);
        plot([Xtop Xtop],[oldyvs yvs],'Color','k','LineStyle',':', 'LineWidth',2);
    else
        yvs = temp(3);
    end
    X = [Xtop Xbot];
    plot(X,[yvs,yvs],'Color','k','LineStyle',':', 'LineWidth',2);
    Xtop = Xbot;
end

% plot the last layer in the litho1.0 model
temp = str2num(fgetl(lithoXD));
Xbot = Xtop + 30;
oldyvs = yvs;
yvs = temp(3);
plot([Xtop Xtop],[oldyvs yvs],'Color','k','LineStyle',':', 'LineWidth',2);
X = [Xtop Xbot];
plot(X,[yvs,yvs],'Color','k','LineStyle',':', 'LineWidth',2);

hold off

%% plot the rho model
lithoXD = fopen(lithomodel);
temp = fgetl(lithoXD);
nElem = str2num(temp)-1;
Xtop = 0;

subplot(1,4,1);
hold on
for i = 1:nElem
    temp = str2num(fgetl(lithoXD));
    depth = temp(1);
    Xbot = Xtop + depth;
    if Xtop ~= 0
        oldyrho = yrho;
        yvs = temp(3)*1000;
        yvp = 0.9409e3 + yvs*(2.0947 + yvs*(-0.8206e-3 + yvs*(0.2683e-6 - 0.0251e-9*yvs)));
        yrho = yvp*(1.6612 + yvp*(-0.4721e-3 + yvp*(0.0671e-6 + yvp*(-0.0043e-9 + 0.000106e-12*yvp))));
        yrho = yrho/1000;
        plot([Xtop Xtop],[oldyrho yrho],'Color','k','LineStyle',':', 'LineWidth',2);
    else
        yvs = temp(3)*1000;
        yvp = 0.9409e3 + yvs*(2.0947 + yvs*(-0.8206e-3 + yvs*(0.2683e-6 - 0.0251e-9*yvs)));
        yrho = yvp*(1.6612 + yvp*(-0.4721e-3 + yvp*(0.0671e-6 + yvp*(-0.0043e-9 + 0.000106e-12*yvp))));
        yrho = yrho/1000;
    end
    X = [Xtop Xbot];
    
    plot(X,[yrho,yrho],'Color','k','LineStyle',':', 'LineWidth',2);
    Xtop = Xbot;
end

% plot the last layer in the litho1.0 model
temp = str2num(fgetl(lithoXD));
Xbot = Xtop + 30;
oldrho = yrho;
yvs = temp(3)*1000;
yvp = 0.9409e3 + yvs*(2.0947 + yvs*(-0.8206e-3 + yvs*(0.2683e-6 - 0.0251e-9*yvs)));
yrho = yvp*(1.6612 + yvp*(-0.4721e-3 + yvp*(0.0671e-6 + yvp*(-0.0043e-9 + 0.000106e-12*yvp))));
yrho = yrho/1000;
plot([Xtop Xtop],[oldrho yrho],'Color','k','LineStyle',':', 'LineWidth',2);
X = [Xtop Xbot];
plot(X,[yrho,yrho],'Color','k','LineStyle',':', 'LineWidth',2);

hold off

%% plot the Vp/Vs model
lithoXD = fopen(lithomodel);
temp = fgetl(lithoXD);
nElem = str2num(temp)-1;
Xtop = 0;

subplot(1,4,4);
hold on
for i = 1:nElem
    temp = str2num(fgetl(lithoXD));
    depth = temp(1);
    Xbot = Xtop + depth;
    if Xtop ~= 0
        oldyvpvs = yvpvs;
        yvs = temp(3)*1000;
        yvp = 0.9409e3 + yvs*(2.0947 + yvs*(-0.8206e-3 + yvs*(0.2683e-6 - 0.0251e-9*yvs)));
        yvpvs = yvp/yvs;
        %yvpvs = 2.0947 + yvs*(-1.6412e-3 + yvs*(0.8049e-6 - 0.1004e-9*yvs));
        plot([Xtop Xtop],[oldyvpvs yvpvs],'Color','k','LineStyle',':', 'LineWidth',2);
    else
        yvs = temp(3)*1000;
        yvp = 0.9409e3 + yvs*(2.0947 + yvs*(-0.8206e-3 + yvs*(0.2683e-6 - 0.0251e-9*yvs)));
        yvpvs = yvp/yvs;
        %yvpvs = 2.0947 + yvs*(-1.6412e-3 + yvs*(0.8049e-6 - 0.1004e-9*yvs));
    end
    X = [Xtop Xbot];
    
    plot(X,[yvpvs,yvpvs],'Color','k','LineStyle',':', 'LineWidth',2);
    Xtop = Xbot;
end

% plot the last layer in the litho1.0 model
temp = str2num(fgetl(lithoXD));
Xbot = Xtop + 30;
oldyvpvs = yvpvs;
yvs = temp(3)*1000;
yvp = 0.9409e3 + yvs*(2.0947 + yvs*(-0.8206e-3 + yvs*(0.2683e-6 - 0.0251e-9*yvs)));
yvpvs = yvp/yvs;
%yvpvs = 2.0947 + yvs*(-1.6412e-3 + yvs*(0.8049e-6 - 0.1004e-9*yvs));
plot([Xtop Xtop],[oldyvpvs yvpvs],'Color','k','LineStyle',':', 'LineWidth',2);
X = [Xtop Xbot];
plot(X,[yvpvs,yvpvs],'Color','k','LineStyle',':', 'LineWidth',2);

hold off
%% save the plot in PDF format
% fig = gcf;
% saveFig('fig6_pathavgModel_XD.pdf', '/Users/sxue3/Documents/Figures/fig/', 1, fig);
